title: Buttons
status: ready
collated: true
notes: "The csu-button class can be applied to both the ```<button>``` and ```<p>``` tags and can be coloured using class modifiers. Hover states are done using box-shadows."
context:
  modifier: default
  text: Regular Button
  class: csu-button
variants:
  - name: Wide Button
    context:
      class: csu-button csu-btn-wide
      text: Wide Button
  - name: Large Button
    context:
      class: csu-button csu-btn-large
      text: Large Button
  - name: Full Button
    context:
      class: csu-button csu-btn-full
      text: Full Button
  - name: Group
    context:
      modifier: Grouped Buttons
      class: csu-button
      text: Group Button
  - name: Group
    context:
      modifier: Coloured Buttons
      class: csu-button csu-green
      text: Colour Button
