title: Unordered Lists
status: ready
collated: true
notes: Unordered lists can have a variety of bullets applied to them using various classes. 
context:
  modifier: default
  text: Example List Item
variants:
  - name: Circle
    context:
      modifier: Circle
      class: circle
      text: Circle List Items
  - name: Disc
    context:
      modifier: Disc
      class: disc
      text: Disc List Items
  - name: Square
    context:
      modifier: Square
      class: square
      text: Square List Items
  - name: Checklist
    context:
      modifier: Checklist
      class: checklist
      text: Checklist List Items
  - name: APA
    context:
      modifier: APA Referencing
      class: apa
      text: APA Referencing List Items
      ref1: "Conole, G. (2009). <em>Personalisation through technology-Enhanced learning</em>. In J. O’Donoghue (Ed.), Technology-Supported Environments for Personalized Learning: Methods and Case Studies (pp. 1-15). London: IGI Global. doi:10.4018/978-1-60566-884-0.ch001"
      ref2: "Gibson, D., Ostashewski, N., Flintoff, K., Grant, S., &amp; Knight, E. (2013). Digital badges in education. <em>Education and information technologies, 20</em>(2), 403-410. doi:10.1007/s10639-013-9291-7"
      ref3: "Irwin, B., Hepplestone, S., Holden, G., Parkin, H. J., & Thorpe, L. (2013). Engaging students with feedback through adaptive release. Innovations in Education & Teaching International, 50(1), 51-61. doi:10.1080/14703297.2012.748333"
