title: Gradient Modifiers
status: ready
collated: true
notes: Gradients are still a work in progress but will be included in the next theme update. There are two gradient types - colour to dark + direction uses the ```csu-COLOURNAME-gradient-DIRECTION``` convention. The other uses a ```csu-grad-COLOURNAME-COLOURNAME``` where the COLOURNAME can be set to any colour from the Material Pallette.
context:
  modifier: blue
variants:
  - name: Green
    context:
      modifier: green
  - name: grey
    context:
      modifier: grey
  - name: ochre
    context:
      modifier: ochre
  - name: orange
    context:
      modifier: orange
  - name: purple
    context:
      modifier: purple
  - name: red
    context:
      modifier: red
  - name: brand
    context:
      modifier: black
  - name: brand
    context:
      modifier: red
  - name: brand
    context:
      modifier: brown
  - name: brand
    context:
      modifier: orange
  - name: brand
    context:
      modifier: light
